# This is a basic workflow to help you get started with Actions

name: Carrye-RDP

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Copie o Codigo do PowerShell'
        required: true
      pincode:
        description: 'Senha de 6 numeros'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD 
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: ./timeout.ps1

  
    
